export const FETCH_HOT_DEALS_PENDING = 'FETCH_HOT_DEALS_PENDING';
export const FETCH_HOT_DEALS_FULFILLED = 'FETCH_HOT_DEALS_FULFILLED';
export const FETCH_HOT_DEALS_REJECTED = 'FETCH_HOT_DEALS_REJECTED';

